name: Update Docs and README on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    if: github.repository == 'leftkats/awesome-greek-tech-jobs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python and dependencies
        run: uv sync --frozen

      - name: Sync Content
        run: |
          uv run python -m scripts.generate_readme
          uv run python -m scripts.generate_index

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add readme.md index.html

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(📚): auto-update docs with fresh content [skip ci]"
            git push origin main
          fi
